### PR TITLE
client, common, server: Ignore some YouTube errors, implement YouTube livestream exception

### LINKED ISSUE #801: Youtube proxy spams errors
```
internal server error: youtube proxy on id=`H1pM4H--mrM`: Error extracting sts from embedded url response: common.StatusError{Err:(*errors.errorString)(0xc4223840a0), Code:500}
````

@Chiiruno 
I don't know what this is, but please fix this.

### PR DESCRIPTION
**Pull request by ghost**
Fixes #801
I looked into implementing livestreaming by defaulting livestreams to noembed, but unfortunately they don't support it either.
As a matter of fact, IIRC YouTube doesn't like embedded livestreams no matter what.
Anyway, I implemented an error case if someone links a livestream, so it doesn't give you that error to your email too.

### CODE REVIEW

File: go/src/meguca/server/router.go [hunk 1]
```diff
@@ -43,8 +43,9 @@ var (
 
 	isTest bool
 
-	errNoYoutubeVideo = common.StatusError{errors.New("no YouTube video found"),
-		404}
+	errYouTubeLive = common.StatusError{errors.New("YouTube video is a livestream"), 501}
```
Comment (bakape) [inline go/src/meguca/server/router.go]: >501 
This will get logged as a server error. Change to a 415.

These should also be converted to error functions, that take a youtube ID and output an error that includes the ID in the message.

File: go/src/meguca/server/router.go [hunk 2]
```diff
@@ -256,65 +257,121 @@ func healthCheck(w http.ResponseWriter, r *http.Request) {
...
 		return nil
 	}()
+
 	if err != nil {
 		if !common.CanIgnoreClientError(err) {
-			err = common.StatusError{
-				fmt.Errorf("youtube proxy on id=`%s`: %s",
-					extractParam(r, "id"), err),
-				500,
+			switch err.(common.StatusError).Code {
```
Comment (bakape) [inline go/src/meguca/server/router.go]: Will panic, if types do not match.

**Review by bakape — DISMISSED** [review]

**Comment by Chiiruno** [comment]
@bakape Ready for merging again.

**Comment by Chiiruno** [comment]
Never mind, looks like I can do it.
Didn't see the invite.

**Review by ghost — COMMENTED** [review]
Fixed the issues.

**Comment by Chiiruno** [comment]
I guess I was supposed to approve your review?

**Comment by Chiiruno** [comment]
Okay, PR authors can't approve their own PR.
That makes sense, and makes for good code quality.
You wouldn't believe how much I check my code and you still find things.

**Review by bakape — APPROVED** [review]
