### PR TITLE
client: Add capturing event handler for broken images

### LINKED ISSUE #830: Empty image frame
Every now and then, an image someone uploads doesn't show, and instead is an empty image frame.
I think the console error said something about it not existing on the server.
My theory is that the client is trying to load the image before it exists, and doesn't retry on on async function to eventually load it properly.

### PR DESCRIPTION
**Pull request by Chiiruno**
Fixes #830

### CODE REVIEW

**Comment by Chiiruno** [comment]
Okay, we should be good now.

**Comment by Chiiruno** [comment]
I may be able to check the image tag itself instead, don't merge yet.

**Comment by Chiiruno** [comment]
Hmm, I'm not sure how I want to do this. Right now this PR works, or should, but polling the server isn't the ideal situation, but I'm not sure how to implement onerror properly in this instance.
See: https://stackoverflow.com/questions/3984287/how-to-show-alternate-image-if-source-image-is-not-found-onerror-working-in-ie

**Comment by Chiiruno** [comment]
Well, currently it only ensures that if you click, it loads, which also reloads the thumbnail.

**Comment by Chiiruno** [comment]
Yeah, this isn't going to cut it.
Maybe we could add `onload` and `onerror` to each image in the client whenever it's first aware of an image (where is that?), and then add an event listener to reload X amount of times before giving up and maybe adding an attribute which it checks for and just returns if the attribute exists?

**Comment by bakape** [comment]
I'd just use event delegation. Can't you listen for 502 on the entire document and then check, if the target is actually an image we can then reload?

**Comment by Chiiruno** [comment]
Some anon said something about image load errors not bubbling or something.
Do you think it can be done? Ideas on how you would implement it?

**Comment by bakape** [comment]
Are you sure they don't buble? They should like any error.

**Comment by Chiiruno** [comment]
I'll link some articles in a bit if I can find them, but image load errors are special in that they don't I think.
Or, at least, `onerror` and `onload` are.
At any rate, we would have to define both of them anyway, which maybe is why.

**Comment by Chiiruno** [comment]
Note: I need to apply something similar to the upload process so we don't get stuck with infinite uploads.

**Comment by Chiiruno** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror
https://stackoverflow.com/questions/22500648/how-to-listen-to-the-error-event-of-all-images
https://stackoverflow.com/questions/14983988/is-bubbling-available-for-image-load-events
Looks like we can do a capturing event listener.

**Comment by bakape** [comment]
Great.

**Comment by Chiiruno** [comment]
Not really sure if this is the best way to do this, but it's all I'm able to figure out for now.

File: client/posts/posting/image.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+        return
+    }
+
+    const src = el.getAttribute("src")
+
+    if (src.includes("?bs=")) {
+        return
+    }
+
+    for (var i = 0;; i++) {
```
Comment (Chiiruno) [inline client/posts/posting/image.ts]: Note: I tried limiting it, but for some reason everything behaves weirdly in async functions and it would just skip over, or not actually do the await or something.

File: client/posts/posting/image.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+        
+        // Force refresh the cache
+        el.setAttribute("src", `${src}?bs=${i}`)
+        await new Promise(resolve => setTimeout(resolve, 2000))
+    }
+}
+
+// Bind listeners
+export default () => {
+    document.addEventListener("error", onImageErr, true)
```
[the remark this answers is not in the document]
Comment (Chiiruno) [reply client/posts/posting/image.ts]: It does work, and while I'd like to eliminate the initial double GET due to async, there is this error: `Unable to preventDefault inside passive event listener invocation.`

[the remark this answers is not in the document]
Comment (Chiiruno) [reply client/posts/posting/image.ts]: Do I just get rid of preventDefault or do something else?

**Comment by Chiiruno** [comment]
@bakape Is this ready for merging?

**Comment by bakape** [comment]
dum github; reposting:

Does the prevent default keep the error from showing up inside the error console? If yes, keep it and remove passive but only after you verify it's an image we need to refetch. Otherwise remove the preventdefault.

**Comment by Chiiruno** [comment]
The error only shows if we have `preventDefault()` and are passive.

>remove passive but only after you verify it's an image we need to refetch

You can do this inside of the event function?

File: client/posts/posting/image.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
+// Reload image if error
+// Handle event if image error
+async function onImageErr(e: Event) {
+    const el = (e.target as HTMLImageElement)
+
+    if (el.tagName !== "IMG" || (el.complete && el.naturalWidth !== 0)) {
+        return
+    }
+
```
Comment (bakape) [inline client/posts/posting/image.ts]: I meant here.

Comment (Chiiruno) [reply client/posts/posting/image.ts]: If you're talking about that, we should be able to remove passive, and keep preventDefault, and have the same functionality.

**Comment by bakape** [comment]
Yes,
